[target.x86_64-apple-darwin]
rustflags = ["-C", "link-args=-Wl,-rpath,/opt/homebrew/lib,-rpath,/usr/local/lib"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-args=-Wl,-rpath,/opt/homebrew/lib,-rpath,/usr/local/lib"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-Wl,-rpath,/usr/lib,-rpath,/usr/local/lib"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-Wl,-rpath,/usr/lib,-rpath,/usr/local/lib"]
